openapi: 3.0.3
info:
  title: Soil Management API's
  version: 1.0.0
  description: Backend services for a Co-Working Space Management System
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /bookings/:
    get:
      operationId: bookings_list
      tags:
      - bookings
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bookings'
          description: ''
    post:
      operationId: bookings_create
      tags:
      - bookings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bookings'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bookings'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bookings'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookings'
          description: ''
  /bookings/{id}/:
    get:
      operationId: bookings_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bookings.
        required: true
      tags:
      - bookings
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bookings'
          description: ''
    put:
      operationId: bookings_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bookings.
        required: true
      tags:
      - bookings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingsPatch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BookingsPatch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BookingsPatch'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingsPatch'
          description: ''
    patch:
      operationId: bookings_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bookings.
        required: true
      tags:
      - bookings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBookingsPatch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBookingsPatch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBookingsPatch'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingsPatch'
          description: ''
    delete:
      operationId: bookings_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bookings.
        required: true
      tags:
      - bookings
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /spaces/:
    get:
      operationId: spaces_list
      tags:
      - spaces
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Space'
          description: ''
    post:
      operationId: spaces_create
      tags:
      - spaces
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Space'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Space'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Space'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: ''
  /spaces/{id}/:
    get:
      operationId: spaces_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this space.
        required: true
      tags:
      - spaces
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: ''
    put:
      operationId: spaces_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this space.
        required: true
      tags:
      - spaces
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Space'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Space'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Space'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: ''
    patch:
      operationId: spaces_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this space.
        required: true
      tags:
      - spaces
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSpace'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSpace'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSpace'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
          description: ''
    delete:
      operationId: spaces_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this space.
        required: true
      tags:
      - spaces
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /spaces/available_spaces/:
    get:
      operationId: spaces_available_spaces_list
      parameters:
      - in: query
        name: max_price
        schema:
          type: number
          format: float
        description: Filter spaces within a maximum price range
      - in: query
        name: min_capacity
        schema:
          type: integer
        description: Filter spaces with a minimum capacity
      - in: query
        name: type
        schema:
          type: string
        description: Filter spaces by type (e.g., 'meeting_room')
      tags:
      - spaces
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Space'
          description: ''
components:
  schemas:
    Bookings:
      type: object
      properties:
        username:
          type: string
          maxLength: 255
        user_email:
          type: string
          format: email
          maxLength: 254
        space_id:
          type: integer
          writeOnly: true
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          readOnly: true
      required:
      - end_time
      - space_id
      - start_time
      - status
      - user_email
      - username
    BookingsPatch:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusEnum'
    PatchedBookingsPatch:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusEnum'
    PatchedSpace:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        type:
          $ref: '#/components/schemas/TypeEnum'
        capacity:
          type: integer
          maximum: 2147483647
          minimum: 0
        price_per_hour:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        is_available:
          type: boolean
    Space:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        type:
          $ref: '#/components/schemas/TypeEnum'
        capacity:
          type: integer
          maximum: 2147483647
          minimum: 0
        price_per_hour:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        is_available:
          type: boolean
      required:
      - capacity
      - id
      - name
      - price_per_hour
      - type
    StatusEnum:
      enum:
      - pending
      - confirmed
      - completed
      - cancelled
      type: string
      description: |-
        * `pending` - Pending
        * `confirmed` - Confirmed
        * `completed` - Completed
        * `cancelled` - Cancelled
    TypeEnum:
      enum:
      - private_office
      - meeting_room
      - hot_desk
      type: string
      description: |-
        * `private_office` - Private Office
        * `meeting_room` - Meeting Room
        * `hot_desk` - Hot Desk
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
